name: Publish Mod

# Run when a new release is... released
on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          token: ${{secrets.THUNDERSTORE_TOKEN}}
          community: riskofrain2 
          namespace: AshAxolotl
          name: Random_Item_Renames
          description: a few stupid item renames 
          version: "1.3" # ${{github.ref_name}} # Use the tag as the package version
          nsfw: true
          categories: | 
            language